name: generic_text_field_states
description: Generic text field states for use with creating a single text field widget for the whole app.
version: 1.0.0
repository: https://github.com/godfreycomputing/text_field_states
environment:
  sdk: '>=2.15.1 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  build_runner: ^2.1.7
  freezed: ^1.1.1
  lints: ^1.0.0
  test: ^1.16.0
dependencies: 
  flutter_riverpod: ^1.0.3
  freezed_annotation: ^1.1.0
  intl: ^0.17.0
  simple_validations: '>=1.0.0 <2.0.0'
